### PR TITLE
get_mediawiki_variable() otputs error message to console instead of null

### PR DESCRIPTION
**Pull request by pastakhov**

### CODE REVIEW

**Comment by pastakhov** [comment]
Need to find another solution, I see in the docker console for the maintenance scripts (ran as www user)
```
web_1            | /functions.sh: line 3: /dev/console: Permission denied
web_1            | /functions.sh: line 3: /dev/console: Permission denied
```

**Comment by vedmaka** [comment]
Maybe it's a very straightforward solution, but how do you feel about setting zero verbosity level at `getMediawikiSettings.php` to prevent warnings and notices from cluttering the output ?

**Comment by pastakhov** [comment]
It seems it works wrong in k8 only or Canasta, On my computer it sends all errors messages to stderr instead of variables (I mean without my previous patch to send it to /dev/null or this patch)

**Comment by pastakhov** [comment]
There is no issue at least with Taqasta image

**Pull request closed without merging**
